fixed port and updated version
dbarranco/docker-csgo pull request #1
Opened 2018-08-28 03:28 UTC by lennard7001

I updated the docker compose version from 2 => 3 and I fixed the wrong port variable

2018-08-29 10:33 UTC, dbarranco commented
Hi @lennard7001 

First of all, thank you so much for your contribution.
I'm sorry, but I can not accept the contribution, as adding the `GAME_SERVER_LOGIN_TOKEN` will make the container don't work out-of-the-box.
By the moment I would prefer to leave the environment variables empty and let the user the option to configure them for public servers. Note that for private-LAN servers that env. var won't be needed.

If you remove that part, I will be happy to accept the update from the docker-compose v2 to v3.

Thanks again!
David

2018-08-29 10:44 UTC, dbarranco commented on docker-compose.yml
> +    image: "dbaus/csgo:latest"
Could you please leave this as single quotes?
Would like to have the convention along all the docker-compose file.

Thanks! :)

2018-08-31 01:20 UTC, lennard0711 commented
Ignore the useless comments in the middle pls. I tried to test something and I were stupid. And I removed the `MAINTAINER` thing since it's deprecated

2018-08-31 10:57 UTC, dbarranco requested changes

2018-08-31 10:57 UTC, dbarranco commented on Dockerfile
> -MAINTAINER David Barranco <d.baus@outlook.com>
As the MAINTAINER label it's deprecated, you could set:

```
LABEL maintainer="arp4@protonmail.com"
```

:D 
The rest LGTM!

2018-08-31 10:58 UTC, dbarranco requested changes

2018-08-31 10:58 UTC, dbarranco commented on docker-compose.yml
> +# More infos over here: https://github.com/dbarranco/docker-csgo#environment-variables
typo: `s/infos/info`

2018-09-01 17:30 UTC, lennard7001 commented on docker-compose.yml
> +# More infos over here: https://github.com/dbarranco/docker-csgo#environment-variables
Ooops the german came through

2018-09-01 17:34 UTC, lennard7001 commented
Everything should be done now :)

2018-09-01 17:42 UTC, dbarranco commented
Looks good to me!
Thanks for the contribution :)

2018-09-01 17:42 UTC, merged